--- 
title: ""
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
---

# Fitopatometría {-}

Rama de la fitopatología  que se ocupa de la teoría y la práctica de la evaluación cuantitativa de enfermedades (y/o patógenos). 


**Nivel de planta individual**

- Severidad: medida de la cantidad de enfermedad por unidad de muestreo (planta, m² de cultivo, fruto, etc.) . En fitopatología es comúnmente definida como el área (volumen) de tejido enfermo dividido por el total del área (volumen) (x100 para obtener un valor en porcentaje)

**Nivel de parcela / lote**

- Incidencia: número de unidades muestreales (plantas) que están enfermas o infectadas por un agente patogénico. Expresado como un porcentaje (%) o proporción (0->1) del número total de unidades evaluadas.

- Indice de severidad: Estimación de severidad usando una escala de severidad que comprende una serie de intervalos de rangos numéricos. 

Por ej: 

```{r eval=FALSE}
grado  rango de severidad
-----  ------------------
    0                   0
    1              0<=25%
    2             25<=50%
    3             50<=75%
    4            75<=100%
```

La propuesta de @madden2007study (Cap. 2, pág. 20) es corregir por el punto medio del rango de severidad:

$IS(\%)=\frac {\sum frecuencia \: de \: grado\: \times\: punto \: medio \: del \: grado \:de\: escala} {total \: plantas \: evaluadas \times 100}$


**Nivel de región**

- Prevalencia: número de unidades de muestreo geográficas (lotes, campos, municipios, estados, regiones, etc.) donde se detectó una enfermedad o un patógeno, dividido por el número total de unidades de muestreo geográficas evaluadas.